jobs:
  - name: development
    max_in_flight: 1
    plan: 
      - get: https://github.com/simonkesh/terraconcourrse-demo
        trigger: true
      - task: get-tako
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: terraconcourrse-demo
          ruun:
            path: sh
            args:
              - exc
              - |
                export AWS_ACCESS_KEY_ID="AKIAY7J2LW7I4IJOSIMZ"
                export AWS_SECRET_ACCESS_KEY="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"
                export AWS_DEFAULT_REGION="us-east-1"
                terraform init
                terraform 



      